import type { Listing } from "./types";

const COLORS = [
  "#2f6df6",
  "#10b981",
  "#f59e0b",
  "#ef4444",
  "#8b5cf6",
  "#ec4899",
  "#0ea5e9",
  "#14b8a6",
];

function color(i: number) {
  return COLORS[i % COLORS.length];
}

/**
 * Seed listings spread across several US metros so the geo-search has
 * something to filter. Coordinates are approximate city centers.
 */
export const SEED_LISTINGS: Listing[] = [
  {
    id: "s1",
    kind: "has-room",
    name: "Maya",
    age: 27,
    headline: "Sunny 2BR in Brooklyn, 1 room open",
    bio: "Designer, early riser, love plants and quiet weeknights. Looking for a tidy, friendly roommate to share a Williamsburg apartment.",
    city: "Brooklyn, NY",
    lat: 40.6782,
    lng: -73.9442,
    budget: 1450,
    moveIn: "2026-07-01",
    tags: ["Non-smoker", "Pet-friendly", "LGBTQ+ friendly"],
    avatarColor: color(0),
    verified: true,
  },
  {
    id: "s2",
    kind: "needs-room",
    name: "Devin",
    age: 24,
    headline: "Grad student looking near campus",
    bio: "Starting a master's at NYU this fall. Clean, social, plays guitar (with headphones!). Budget is flexible for the right vibe.",
    city: "Manhattan, NY",
    lat: 40.7831,
    lng: -73.9712,
    budget: 1600,
    moveIn: "2026-08-15",
    tags: ["Student", "Non-smoker", "Early riser"],
    avatarColor: color(1),
  },
  {
    id: "s3",
    kind: "has-room",
    name: "Priya",
    age: 31,
    headline: "Room in a quiet Jersey City condo",
    bio: "Software engineer, WFH most days. Great natural light, gym in building, 10 min PATH to the city.",
    city: "Jersey City, NJ",
    lat: 40.7178,
    lng: -74.0431,
    budget: 1300,
    moveIn: "2026-07-15",
    tags: ["WFH friendly", "Non-smoker", "Gym"],
    avatarColor: color(2),
  },
  {
    id: "s4",
    kind: "has-room",
    name: "Carlos",
    age: 29,
    headline: "Mission District room, super social house",
    bio: "Three of us in a fun 4BR, looking for the last roommate. Taco nights, board games, bikes welcome.",
    city: "San Francisco, CA",
    lat: 37.7599,
    lng: -122.4148,
    budget: 1700,
    moveIn: "2026-07-01",
    tags: ["Social", "Pet-friendly", "Cyclist"],
    avatarColor: color(3),
  },
  {
    id: "s5",
    kind: "needs-room",
    name: "Aiko",
    age: 26,
    headline: "Nurse seeking calm place in the Bay",
    bio: "Work rotating shifts at UCSF, so I value a quiet home. Spotless, low-key, love cooking on days off.",
    city: "Oakland, CA",
    lat: 37.8044,
    lng: -122.2712,
    budget: 1500,
    moveIn: "2026-09-01",
    tags: ["Healthcare", "Quiet", "Non-smoker"],
    avatarColor: color(4),
  },
  {
    id: "s6",
    kind: "has-room",
    name: "Jordan",
    age: 23,
    headline: "East Austin room, musicians welcome",
    bio: "Big house with a backyard and a little home studio. Looking for someone creative and chill.",
    city: "Austin, TX",
    lat: 30.2672,
    lng: -97.7431,
    budget: 950,
    moveIn: "2026-07-10",
    tags: ["Musician", "Pet-friendly", "Backyard"],
    avatarColor: color(5),
    verified: true,
    boosted: true,
  },
  {
    id: "s7",
    kind: "needs-room",
    name: "Sofia",
    age: 28,
    headline: "Remote marketer relocating to Austin",
    bio: "Moving from Chicago for the sunshine. Friendly, organized, weekend hiker. Open to most neighborhoods.",
    city: "Austin, TX",
    lat: 30.2849,
    lng: -97.7341,
    budget: 1100,
    moveIn: "2026-08-01",
    tags: ["WFH friendly", "Hiker", "Non-smoker"],
    avatarColor: color(6),
    verified: true,
  },
  {
    id: "s8",
    kind: "has-room",
    name: "Liam",
    age: 30,
    headline: "Wicker Park 2BR, dog-friendly",
    bio: "I have a golden retriever named Biscuit. Looking for a dog-loving roommate for a bright apartment near the Blue Line.",
    city: "Chicago, IL",
    lat: 41.9088,
    lng: -87.6796,
    budget: 1050,
    moveIn: "2026-07-01",
    tags: ["Pet-friendly", "Near transit", "Social"],
    avatarColor: color(7),
  },
  {
    id: "s9",
    kind: "has-room",
    name: "Nadia",
    age: 25,
    headline: "Capitol Hill room, plant-filled & cozy",
    bio: "Barista and ceramicist. Looking for a creative, considerate roommate. Lots of natural light and good coffee.",
    city: "Seattle, WA",
    lat: 47.6253,
    lng: -122.3222,
    budget: 1200,
    moveIn: "2026-07-20",
    tags: ["Non-smoker", "Creative", "Coffee"],
    avatarColor: color(0),
  },
  {
    id: "s10",
    kind: "needs-room",
    name: "Marcus",
    age: 33,
    headline: "Engineer seeking room in Seattle",
    bio: "Quiet, reliable, gym every morning. Relocating for a new job downtown. Looking for a long-term place.",
    city: "Seattle, WA",
    lat: 47.6062,
    lng: -122.3321,
    budget: 1400,
    moveIn: "2026-08-10",
    tags: ["Professional", "Early riser", "Non-smoker"],
    avatarColor: color(1),
  },
  {
    id: "s11",
    kind: "has-room",
    name: "Bianca",
    age: 27,
    headline: "Silver Lake room w/ rooftop access",
    bio: "Film editor, love hosting dinners. The place has a great rooftop and is walkable to coffee + tacos.",
    city: "Los Angeles, CA",
    lat: 34.0837,
    lng: -118.2701,
    budget: 1350,
    moveIn: "2026-07-05",
    tags: ["Social", "Pet-friendly", "Rooftop"],
    avatarColor: color(2),
  },
  {
    id: "s12",
    kind: "needs-room",
    name: "Theo",
    age: 22,
    headline: "Recent grad job-starting in LA",
    bio: "First job out of school, super easygoing. Into surfing and cooking. Looking for friendly roommates on the west side.",
    city: "Santa Monica, CA",
    lat: 34.0195,
    lng: -118.4912,
    budget: 1250,
    moveIn: "2026-09-01",
    tags: ["Student", "Surfer", "Non-smoker"],
    avatarColor: color(3),
  },
];
